---
title: "Plots - static"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

## Plots - interactive
Plot data. Use ggplot library for nice plots and ggplotly to make them interactive.
```{r}
# load data
angles <- read.table(file = './data/angles.csv', sep = ';', dec = '.', header = T)

# melt data for plotting to different structure
angles_melted <- melt(angles, measure.vars = angle_names, variable.name = 'angle_name', value.name = 'angle')

# plot data
for(class in class_names) {
  # subset data for given class
  angles_plot <- angles_melted[angles_melted$class == class, ]
  
  # create and save static plots
  density_plot_static <- ggplot(angles_plot, mapping = aes(x = angle, colour = angle_name)) + 
                          geom_density(adjust=2) + ggtitle(paste('NtC class:', class))
  path <- paste0("./plots_static/densities/Class ", class, ".svg")
  ggsave(filename = path, plot = density_plot_static, units  = 'cm', width = 15, height = 10, dpi = 300)
  
  # create and save interactive plots
  density_plot_interactive <- ggplotly(density_plot_static)
  path <- paste0("./plots_interactive/densities/Class ", class, ".html")
  path <- file.path(normalizePath(dirname(path)),basename(path))
  saveWidget(widget = density_plot_interactive, selfcontained = F, libdir = './plotly_libraries', file = path)
}

```

View interactive plots.
```{r}
plot_paths <- list.files(path = "./plots_interactive/densities/", pattern = 'Class ', full.names = TRUE)
plot_files <- list.files(path = "./plots_interactive/densities/", pattern = 'Class ', full.names = FALSE)
plot_names <- substr(x = plot_files, start =  1, stop = nchar(plot_files)-5)
names(plot_paths) <- plot_names
bsselect(vector = plot_paths, type = "iframe", selected = "Class A", live_search = TRUE, show_tick = TRUE)
```
